### ISSUE TITLE
number_format used incorrectly in Order.php

### ISSUE THREAD

**Issue by n-scott** [fraudlabspro/fraudlabspro-php#1]
Line 67 in Order.php needs to be fixed so that the thousands separator is not used, but the decimal separator is used.

Needs to change from:
'amount'			=> (isset($params['order']['amount'])) ? number_format($params['order']['amount'], 2, '', '.') : 0,

to 

'amount'			=> (isset($params['order']['amount'])) ? number_format($params['order']['amount'], 2, '.', '') : 0,

**Comment by chrislim2888** [comment]
Thanks, but this issue already fixed in May'18. Please get the latest version.

**Comment by n-scott** [comment]
I pulled this using composer the same day I opened the case.  Do you have the correct composer version that I need to use to get the most recent code?

This is what I have in my composer file:
"fraudlabspro/fraudlabspro-php": "^2.0"

**Comment by fraudlabspro-com** [comment]
We have updated the package in composer. You may get the latest package by `composer require fraudlabspro/fraudlabspro-php`
